version: '3.8'
name: GadgetGalaxy

services:

  mariadb:
    image: mariadb:10.4.28  
    container_name: mariadb
    ports:
      - "3306:3306"  # Expose MySQL to host
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis to host
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"  # Expose Backend to host
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"  # Expose Frontend to host
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mariadb_data:
